#!/usr/bin/env python3
"""
chipsetmap.py - cross-reference of PicoPower chipset register accesses (index port 24h, data 26h).

Scans the generated listings for `mov ax, IMM` followed (within a few instructions) by a call to one
of the chipset_reg_* helpers or by `out 0x24, ax`, remembers the mask/value operands (`mov dx, IMM`,
`mov bx, IMM`, `mov bl, IMM`) set up before the call, and writes docs/generated/chipset-registers.md:
one row per register index with every access site.  The static init tables (system BIOS
chipset_init_table_94E9, MISER chipset_init_triples / std_chipset_reg_list / dma_page_restore_table)
are decoded as well.

    chipsetmap.py            (run from the bios folder after tools/run.sh)
"""
import re
from collections import defaultdict

LINE = re.compile(r"^([CEF][08]00):([0-9A-F]{4}) ((?:[0-9A-F]{2} )+)\s*([a-z]\S*)\s*(.*)$")
LABEL = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):(?![0-9A-F]{4} )")


def scan(path, module):
    regs = defaultdict(list)
    func = "?"
    window = []  # recent (addr, mnemonic, operands)
    for line in open(path, encoding="utf-8", errors="replace"):
        m = LINE.match(line.rstrip())
        if not m:
            m2 = LABEL.match(line)
            if m2 and not m2.group(1).startswith(("loc_", "ret_", "tbl_")):
                func = m2.group(1)
            continue
        seg, addr, _, mnem, ops = m.groups()
        ops = ops.split(";")[0].strip()
        window.append((addr, mnem, ops))
        window = window[-8:]
        target = None
        if mnem == "call" and ops.startswith("chipset_reg"):
            target = ops
        elif mnem == "out" and ops in ("0x24, ax", "dx, ax") and any(o == "dx, 0x24" for _, mn, o in window if mn == "mov"):
            target = "out 24h"
        if not target:
            continue
        ax = dx = bx = None
        def imm(o, reg):
            if not o.startswith(reg + ", "):
                return None
            v = o[len(reg) + 2:]
            try:
                return int(v, 16) if v.startswith("0x") else int(v)
            except ValueError:
                return None
        for _, mn, o in reversed(window[:-1]):
            if mn == "mov" and imm(o, "ax") is not None and ax is None:
                ax = imm(o, "ax")
            elif mn == "mov" and imm(o, "dx") is not None and dx is None and imm(o, "dx") not in (0x24, 0x26):
                dx = imm(o, "dx")
            elif mn == "mov" and (imm(o, "bx") is not None or imm(o, "bl") is not None) and bx is None:
                bx = imm(o, "bx") if imm(o, "bx") is not None else imm(o, "bl")
            elif mn in ("call", "ret", "retf", "jmp"):
                break
        if ax is None:
            continue
        arg = ""
        if "set_field" in target:
            arg = "mask %04Xh value %s" % (dx or 0, ("%02Xh" % bx) if bx is not None else "BL")
        elif "set_bits" in target or "clear_bits" in target or "test" in target:
            arg = "bits %04Xh" % (dx or 0) if dx is not None else ""
        elif "write" in target:
            arg = ("value %04Xh" % bx) if bx is not None else "value BX"
        regs[ax].append((module, addr, func, target.replace("chipset_reg_", ""), arg))
    return regs


def table_pairs(data, off, count, fmt):
    out = []
    for i in range(count):
        out.append(fmt(data, off + i))
    return out


def main():
    regs = defaultdict(list)
    for mod, path in [("sys", "disasm/sys.asm"), ("miser", "disasm/miser.asm")]:
        for k, v in scan(path, mod).items():
            regs[k].extend(v)
    sysbin = open("build/sys.bin", "rb").read()
    mbin = open("build/miser.bin", "rb").read()
    lines = ["# PicoPower chipset register cross-reference", "",
             "Generated by `tools/chipsetmap.py` from the labelled listings. Index port `24h`, data port `26h` (16-bit).",
             "Register meanings are inferred from usage (see docs/03 and docs/07); no datasheet was available.", "",
             "## Static initialisation tables", ""]
    # sys chipset_init_table_94E9: (index, value) word pairs until ... (the run 94E9-95C4)
    lines.append("### System BIOS `chipset_init_table_94E9` (POST 50h; stored as value, index)")
    lines.append("")
    lines.append("| Index | Value |")
    lines.append("|---|---|")
    o = 0x94E9
    while o + 3 < 0x95C4:
        val = sysbin[o] | sysbin[o + 1] << 8
        idx = sysbin[o + 2] | sysbin[o + 3] << 8
        lines.append("| `%04X` | `%04X` |" % (idx, val))
        o += 4
    lines += ["", "### MISER `chipset_init_triples` (15A6, run_triple_table: value, mask, register)", "", "| Register | Mask | Value |", "|---|---|---|"]
    o = 0x15A6
    while o + 5 < 0x1624:
        val = mbin[o] | mbin[o + 1] << 8
        msk = mbin[o + 2] | mbin[o + 3] << 8
        reg = mbin[o + 4] | mbin[o + 5] << 8
        if reg == 0xFFFF:
            lines.append("| (end of list) | | |")
        else:
            lines.append("| `%04X` | `%04X` | `%04X` |" % (reg, msk, val))
        o += 6
    lines += ["", "### MISER `std_chipset_reg_list` (5144, saved across save-to-disk)", ""]
    o = 0x5144
    regs_l = []
    while True:
        r = mbin[o] | mbin[o + 1] << 8
        if r == 0xFFFF:
            break
        regs_l.append("`%04X`" % r)
        o += 2
    lines.append(", ".join(regs_l))
    lines += ["", "### MISER `dma_page_restore_table` (5520) / `std_dma_shadow_list` (5164)", "",
              "Registers `0201h-0206h` shadow the DMA page registers `81h, 82h, 83h, 87h, 89h, 8Ah` (written back on resume).", "",
              "## Accesses by register", "", "| Register | Accesses (module:address function op argument) |", "|---|---|"]
    for k in sorted(regs):
        cells = "; ".join("%s:%s `%s` %s %s" % (m, a, f, op, arg) for m, a, f, op, arg in regs[k])
        lines.append("| `%04X` | %s |" % (k, cells))
    open("docs/generated/chipset-registers.md", "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print("chipset registers:", len(regs), "indexes,", sum(len(v) for v in regs.values()), "accesses")


if __name__ == "__main__":
    main()
