#!/usr/bin/env python3
"""
misertext.py - decode every piece of text and screen data in the PhoenixMISER module into
docs/generated/miser-text.md: credits, the POWER METER screen, the status phrases, the string-record
lists used by the save-to-disk status box, the box records and the error-message pointer table.

    misertext.py            (run from the bios folder after tools/run.sh)
"""

CP437 = ("░▒▓│┤╡╢╖╕╣║╗╝╜╛┐"
         "└┴┬├─┼╞╟╚╔╩╦╠═╬╧"
         "╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀")


def ch(b):
    if 0x20 <= b < 0x7F:
        return chr(b)
    if 0xB0 <= b <= 0xDF:
        return CP437[b - 0xB0]
    if b == 0:
        return "␀"
    return "\\x%02X" % b


def text(bs):
    return "".join(ch(b) for b in bs)


def w(d, o):
    return d[o] | d[o + 1] << 8


def main():
    d = open("build/miser.bin", "rb").read()
    L = ["# PhoenixMISER text and screen data", "", "Generated by `tools/misertext.py`. CP437 box-drawing characters are shown as Unicode; other control bytes as `\\xNN`.", ""]
    # credits
    L += ["## Credits string (E800:0050)", "", "```", text(d[0x50:0xC2]).replace("␀", "\n"), "```", ""]
    # power meter screen
    L += ["## POWER METER overlay (E800:10EB, four 80-character rows, attribute 71h)", "", "```"]
    for r in range(4):
        L.append(text(d[0x10EB + 80 * r: 0x10EB + 80 * (r + 1)]))
    L += ["```", "", "Status phrases (E800:124D, 24 characters each, chosen by `apm_0A_get_power_status`):", ""]
    for o in (0x124D, 0x1265, 0x127D):
        L.append("- `%04X` `%s`" % (o, text(d[o:o + 24])))
    L.append("")
    # string record lists
    L += ["## String-record lists (E800:415E-45EE)", "",
          "Each record is `id, length, text, NUL`; an id of 0 ends a list. `find_string_record` selects a record by id inside the list a box record points at.", "",
          "| List | Id | Address | Text |", "|---|---|---|---|"]
    o = 0x415E
    lst = o
    while o < 0x45EE:
        rid = d[o]
        if rid == 0:
            o += 1
            lst = o
            continue
        ln = d[o + 1]
        L.append("| `%04X` | %d | `%04X` | `%s` |" % (lst, rid, o, text(d[o + 2:o + 2 + ln])))
        o += ln + 3
    L.append("")
    # box records
    L += ["## Box records (E800:3D9F, 20 bytes each; `draw_box_record`)", "",
          "| Record | Flags | Row | Col | Height | Width | Mono attrs | Colour attrs | Title list | Body list | Frame list |", "|---|---|---|---|---|---|---|---|---|---|---|"]
    for i in range(9):
        o = 0x3D9F + 20 * i
        r = d[o:o + 20]
        L.append("| `%04X` | %04Xh | %d | %d | %d | %d | %s | %s | `%04X` | `%04X` | `%04X` |" % (
            o, w(r, 0), r[2], r[3], r[4], r[5], " ".join("%02X" % x for x in r[6:10]), " ".join("%02X" % x for x in r[10:14]), w(r, 14), w(r, 16), w(r, 18)))
    L += ["", "Flags: 0400h/0800h position from the BIOS cursor (40:50/40:51), 1000h/2000h size from the body text, 4000h/8000h centre on screen; a list address of 0000 means no title/body.", ""]
    # error message ids
    L += ["## Save-to-disk error messages (`std_error_msg_ids`, E800:3E53)", "", "| Code | Record | Text |", "|---|---|---|"]
    for i in range(10):
        p = w(d, 0x3E53 + 2 * i)
        ln = d[p + 1]
        L.append("| %d | `%04X` | `%s` |" % (i, p, text(d[p + 2:p + 2 + ln])))
    L.append("")
    open("docs/generated/miser-text.md", "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("miser-text.md written")


if __name__ == "__main__":
    main()
