#!/usr/bin/env python3
"""
tables.py - decode the fixed data tables of the ROM into docs/generated/tables.md.

  * system BIOS fixed-disk parameter table (F000:E401, 47 types)
  * system BIOS diskette parameter tables (F000:9E9A, 8 x 14 bytes)
  * SETUP field records (F000:014C x 20, F000:1874 x 6)
  * C&T VGA BIOS mode parameter blocks (C000:0047, 64 bytes each) for the standard modes

    tables.py            (run from the bios folder after tools/run.sh)
"""


def w(d, o):
    return d[o] | d[o + 1] << 8


def main():
    s = open("build/sys.bin", "rb").read()
    v = open("build/vga.bin", "rb").read()
    L = ["# Decoded data tables", "", "Generated by `tools/tables.py`.", ""]

    # ---- fixed disk parameter table ----
    L += ["## Fixed-disk parameter table (`hd_param_table`, F000:E401)", "",
          "Type 15 is the reserved (skipped) entry; types 44-47 are patched at run time by the IDENTIFY DEVICE auto-detect (see docs/08).", "",
          "| Type | Cylinders | Heads | Write precomp | Control | Landing zone | Sectors/track | Size (MB) |", "|---|---|---|---|---|---|---|---|"]
    for t in range(1, 48):
        o = 0xE401 + (t - 1) * 16
        cyl, heads, wp, ctl, lz, spt = w(s, o), s[o + 2], w(s, o + 5), s[o + 8], w(s, o + 12), s[o + 14]
        size = cyl * heads * spt * 512 / 1048576.0
        L.append("| %d | %d | %d | %s | %02Xh | %d | %d | %.1f |" % (t, cyl, heads, ("%d" % wp if wp != 0xFFFF else "none"), ctl, lz, spt, size))
    # ---- diskette parameter tables ----
    L += ["", "## Diskette parameter tables (F000:9E9A, 8 x 14 bytes)", "",
          "Standard 11-byte diskette parameter table plus 3 extra bytes (maximum track, data-rate/format bits, drive-type code).", "",
          "| # | Step rate/unload | Head load | Motor off (ticks) | Sector size | Sectors/track | Gap | DTL | Format gap | Fill | Head settle (ms) | Motor start (1/8 s) | Max track | Rate | Type |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for i in range(8):
        o = 0x9E9A + i * 14
        b = s[o:o + 14]
        L.append("| %d | %02Xh | %02Xh | %d | %d | %d | %02Xh | %02Xh | %02Xh | %02Xh | %d | %d | %d | %02Xh | %02Xh |" % (
            i, b[0], b[1], b[2], 128 << b[3], b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13]))
    # ---- SETUP field records ----
    kinds = {0x66: "option list", 0x22: "disk type list", 0x33: "user geometry", 0x44: "user geometry", 0x77: "user geometry", 0x78: "user geometry", 0x55: "with secondary label", 0x11: "text", 0x00: "numeric"}
    L += ["", "## SETUP field records", "", "32-byte records (see docs/05 for the offsets). CMOS = index / bit mask from `+14h/+15h`.", "",
          "| Page | # | Row | Col | Value strings | Next (+4) | Load (+6) | Prev (+C) | Enter (+E) | Store (+10) | Post-store (+12) | CMOS index | Mask | Max | Shift | Default | Type | Kind |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for page, base, n in [(1, 0x014C, 20), (2, 0x1874, 6)]:
        for i in range(n):
            o = base + i * 32
            r = s[o:o + 32]
            L.append("| %d | %d | %d | %d | %04X | %04X | %04X | %04X | %04X | %04X | %04X | %02Xh | %02Xh | %d | %d | %d | %02Xh | %s |" % (
                page, i, r[0], r[1], w(r, 2), w(r, 4), w(r, 6), w(r, 0xC), w(r, 0xE), w(r, 0x10), w(r, 0x12), r[0x14], r[0x15], w(r, 0x16), r[0x18], r[0x19], r[0x1E],
                kinds.get(r[0x1F], "%02Xh" % r[0x1F])))
    # ---- VGA mode parameter blocks ----
    L += ["", "## C&T VGA BIOS mode parameter blocks (64 bytes each)", "",
          "Block index from the VGA (400-line) list at C000:5116; columns/rows/character height are the first bytes, the CRTC values follow the sequencer and misc-output bytes.", "",
          "| Mode | Block | Columns | Rows | Char height | Page size | Seq 1-4 | Misc | H total | H disp end | V total | V disp end | Pixels (derived) | Attr 10h | GC 05/06 |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    lst = v[0x5116:0x5116 + 0x14]
    base = w(v, 0x19E)  # save-area pointer table at C000:019E: entry 0 = video parameter table
    L.insert(len(L) - 2, "Parameter table base: C000:%04X (save-area pointer table at C000:019E, entry 0)." % base)
    L.insert(len(L) - 2, "")
    for mode in range(0x14):
        blk = lst[mode]
        if blk == 0xFF:
            continue
        o = base + blk * 64
        b = v[o:o + 64]
        cols, rows, ch, page = b[0], b[1] + 1, b[2], w(b, 3)
        seq = " ".join("%02X" % x for x in b[5:9])
        misc = b[9]
        crtc = b[10:35]
        htot, hde, vtot_lo, vde_lo, ovf = crtc[0], crtc[1], crtc[6], crtc[0x12], crtc[7]
        vtot = vtot_lo | ((ovf & 1) << 8) | ((ovf & 0x20) << 4)
        vde = vde_lo | ((ovf & 2) << 7) | ((ovf & 0x40) << 3)
        width = (hde + 1) * (8 if (b[5] & 1) else 9)
        height = vde + 1
        attr10 = b[35 + 0x10]
        gc = "%02X/%02X" % (b[55 + 5], b[55 + 6])
        L.append("| %02Xh | %d | %d | %d | %d | %04Xh | %s | %02Xh | %d | %d | %d | %d | %dx%d | %02Xh | %s |" % (
            mode, blk, cols, rows, ch, page, seq, misc, htot, hde, vtot, vde, width, height, attr10, gc))
    # ---- extended (C&T) modes ----
    L += ["", "## C&T extended modes (mode list C000:0ADD, records C000:0AF3)", "",
          "`find_mode_record` looks the mode number up in the list at 0ADD (count at 0ADC); record = 4 bytes (flags, panel byte, pointer to the 64-byte parameter block). Modes in `mode_in_panel_list` use the following record when the flat panel is active.", "",
          "| Mode | Record | Flags | Byte 1 | Block | Columns | Rows | Char height | Seq 1 | Misc | H disp end | V disp end | Pixels (derived) | GC 05/06 |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    cnt = v[0xADC]
    for i in range(cnt):
        mode = v[0xADD + i]
        r = v[0xAF3 + 4 * i: 0xAF3 + 4 * i + 4]
        ptr = r[2] | r[3] << 8
        blk = (ptr - base) // 64 if ptr >= base else -1
        b = v[ptr:ptr + 64]
        crtc = b[10:35]
        hde, vde_lo, ovf = crtc[1], crtc[0x12], crtc[7]
        vde = vde_lo | ((ovf & 2) << 7) | ((ovf & 0x40) << 3)
        width = (hde + 1) * (8 if (b[5] & 1) else 9)
        L.append("| %02Xh | %04X | %02Xh | %02Xh | %d | %d | %d | %d | %02Xh | %02Xh | %d | %d | %dx%d | %02X/%02X |" % (
            mode, 0xAF3 + 4 * i, r[0], r[1], blk, b[0], b[1] + 1, b[2], b[5], b[9], hde, vde, width, vde + 1, b[55 + 5], b[55 + 6]))
    # ---- C&T extension register lists ----
    L += ["", "## C&T extension-register lists (C000:0B4B-0C2A)", "",
          "(XR index, value) pairs, each list terminated by 00 00; selected per mode / panel type by `panel_regs_table_by_type`, `mode_table_select_1E1_1ED` and `panel_config_table_select` (pointer tables at 01DB-0211).", "",
          "| List | Pairs |", "|---|---|"]
    o = 0xB4B
    while o < 0xC2A:
        start = o; pairs = []
        while o + 1 < 0xC2A and not (v[o] == 0 and v[o + 1] == 0):
            pairs.append("%02X=%02X" % (v[o], v[o + 1])); o += 2
        o += 2
        if pairs:
            L.append("| `%04X` | %s |" % (start, " ".join(pairs)))
    open("docs/generated/tables.md", "w", encoding="utf-8", newline="\n").write("\n".join(L) + "\n")
    print("tables.md written")


if __name__ == "__main__":
    main()
