#!/usr/bin/env python3
"""
varsmap.py - RAM variable reference: labels/vars.json (regions, structures) merged with the accessor lists the
disassembler collected while writing the listings (build/<module>-vars.json from `romdis.py --varxrefs`).

    varsmap.py [--out docs/generated/variables.md]        (run from the bios folder after tools/run.sh)

Output: one table per region (offset, name, size, comment, accessed by module:function) plus the structures,
and a list of touched-but-unnamed offsets (region+0xNN) so the naming can be completed.
"""
import argparse
import json
import os
from collections import defaultdict


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="docs/generated/variables.md")
    a = ap.parse_args()
    vars_ = json.load(open("labels/vars.json"))
    xrefs = defaultdict(set)
    for mod in ("sys", "vga", "miser"):
        p = "build/%s-vars.json" % mod
        if os.path.exists(p):
            for k, v in json.load(open(p)).items():
                xrefs[k].update(v)

    def fmt_acc(key):
        acc = sorted(xrefs.get(key, []))
        if not acc:
            return ""
        shown = ", ".join("`%s`" % x for x in acc[:6])
        return shown + (" +%d more" % (len(acc) - 6) if len(acc) > 6 else "")

    out = []
    out.append("# RAM variables and structures\n")
    out.append("Generated by `tools/varsmap.py` from `labels/vars.json` and the accessor lists `tools/romdis.py` collects "
               "while writing the listings. In the listings every memory operand that resolves here is annotated "
               "`region.name` in the comment column; a trailing `?` means the segment register value was assumed from "
               "the module's rules (see `assume` in vars.json) or inherited from only some callers, not proven along the path. "
               "`module:function` lists who reads or writes the variable (unique functions, first six shown).\n")
    unnamed = []
    for rname, r in vars_["regions"].items():
        out.append("## %s (%s-%s)\n" % (rname, r["start"].upper(), r["end"].upper()))
        if r.get("comment"):
            out.append(r["comment"] + "\n")
        vs = r.get("vars", {})
        if vs:
            out.append("| Offset | Name | Size | Meaning | Accessed by |")
            out.append("|---|---|---|---|---|")
            for k in sorted(vs, key=lambda x: int(x, 16)):
                v = vs[k]
                nm = v["name"] if isinstance(v, dict) else v
                sz = v.get("size", 1) if isinstance(v, dict) else 1
                cm = v.get("comment", "") if isinstance(v, dict) else ""
                acc = set()
                for key in xrefs:
                    if key == "%s.%s" % (rname, nm) or key.startswith("%s.%s+" % (rname, nm)):
                        acc |= xrefs[key]
                accs = sorted(acc)
                shown = ", ".join("`%s`" % x for x in accs[:6]) + (" +%d more" % (len(accs) - 6) if len(accs) > 6 else "")
                out.append("| `%s` | `%s` | %d | %s | %s |" % (k.upper(), nm, sz, cm, shown))
            out.append("")
        if r.get("auto") == "ivt":
            rows = sorted((k for k in xrefs if k.startswith("ivt.")), key=lambda k: int(k[7:9], 16))
            if rows:
                out.append("| Vector | Accessed by |")
                out.append("|---|---|")
                for k in rows:
                    out.append("| `%s` | %s |" % (k, fmt_acc(k)))
                out.append("")
        for k in xrefs:
            if k.startswith(rname + "+"):
                unnamed.append((k, sorted(xrefs[k])))
    out.append("## Structures\n")
    for sname, st in vars_.get("structs", {}).items():
        out.append("### %s\n" % sname)
        if st.get("comment"):
            out.append(st["comment"] + "\n")
        out.append("| Offset | Field | Size | Meaning | Accessed by |")
        out.append("|---|---|---|---|---|")
        for k in sorted(st.get("fields", {}), key=lambda x: int(x, 16)):
            f = st["fields"][k]
            acc = set()
            for key in xrefs:
                if key == "%s.%s" % (sname, f["name"]) or key.startswith("%s.%s+" % (sname, f["name"])):
                    acc |= xrefs[key]
            accs = sorted(acc)
            shown = ", ".join("`%s`" % x for x in accs[:6]) + (" +%d more" % (len(accs) - 6) if len(accs) > 6 else "")
            out.append("| `%s` | `%s` | %d | %s | %s |" % (k.upper(), f["name"], f.get("size", 1), f.get("comment", ""), shown))
        out.append("")
        for k in xrefs:
            if k.startswith(sname + "+"):
                unnamed.append((k, sorted(xrefs[k])))
    if unnamed:
        out.append("## Touched but unnamed\n")
        out.append("Offsets the code accesses that have no entry in `labels/vars.json` yet (candidates for naming).\n")
        out.append("| Location | Accessed by |")
        out.append("|---|---|")
        for k, acc in sorted(unnamed):
            out.append("| `%s` | %s |" % (k, ", ".join("`%s`" % x for x in acc[:6]) + (" +%d more" % (len(acc) - 6) if len(acc) > 6 else "")))
        out.append("")
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    open(a.out, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print("%s: %d named keys with accessors, %d unnamed locations" % (a.out, sum(1 for k in xrefs if "+0x" not in k), len(unnamed)))


if __name__ == "__main__":
    main()
